import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { headers } from "next/headers";
import { cookieToInitialState } from "wagmi";
import {CoinMarketProvider} from '../context/context'
import {GunProvider} from '../context/gunContext'
import "./globals.css";
import Web3ModalProvider from "@/context";
import { config } from "@/config";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const initialState = cookieToInitialState(config, headers().get("cookie"));
  return (
    <html lang="en">
      <body className={inter.className}>
        <Web3ModalProvider  initialState={initialState}>
        <GunProvider>
        <CoinMarketProvider>
        {children}
        </CoinMarketProvider>
      </GunProvider>
          
        </Web3ModalProvider>
      </body>
    </html>
  );
}
